name: Build PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install jupyter
          pip install nbconvert
          sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-fonts-extra
          sudo apt-get install pandoc

      - name: Convert notebook to PDF
        run: |
          jupyter nbconvert --to pdf report.ipynb --output report.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: report-pdf
          path: report.pdf
