name: Run Report and Model Analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Run data processing
        run: python src/data_processing.py

      - name: Train model
        run: python src/model_training.py

      - name: Evaluate model
        run: python src/model_evaluation.py

      - name: Generate PDF Report from Jupyter Notebook
        run: jupyter nbconvert --to pdf report.ipynb --output report.pdf

      - name: Upload PDF Report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.pdf

