name: Model Build, Evaluation, and Report Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Processing and Model Training
        run: |
          python src/data_processing.py
          python src/model_training.py
          python src/model_evaluation.py

      - name: Generate Report
        run: |
          jupyter nbconvert --to pdf report.ipynb --output report.pdf

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: report.pdf
